#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const ROOT = process.cwd();
const TEMPLATE_DIR = path.join(ROOT, "templates");

const STAGES = {
  requirements: {
    stage: "stage-01",
    artifact: "pipeline/brief.md",
    template: "brief-template.md",
    gate: {
      agent: "pm",
      acceptance_criteria_count: 0,
      out_of_scope_items: [],
      required_sections_complete: false,
    },
  },
  design: {
    stage: "stage-02",
    artifact: "pipeline/design-spec.md",
    template: "design-spec-template.md",
    gate: {
      agent: "principal",
      arch_approved: false,
      pm_approved: false,
      adr_count: 0,
    },
  },
  review: {
    stage: "stage-05-backend",
    artifact: "pipeline/code-review/by-backend.md",
    template: "review-template.md",
    gate: {
      agent: "codex-team",
      area: "backend",
      review_shape: "matrix",
      required_approvals: 2,
      approvals: [],
      changes_requested: [],
      escalated_to_principal: false,
    },
  },
  qa: {
    stage: "stage-07",
    artifact: "pipeline/test-report.md",
    template: "test-report-template.md",
    gate: {
      agent: "qa",
      all_acceptance_criteria_met: false,
      tests_total: 0,
      tests_passed: 0,
      tests_failed: 0,
      failing_tests: [],
      criterion_to_test_mapping_is_one_to_one: false,
    },
  },
  deploy: {
    stage: "stage-08",
    artifact: "pipeline/runbook.md",
    template: "runbook-template.md",
    gate: {
      agent: "platform",
      pm_signoff: false,
      deploy_requested: false,
      runbook_referenced: false,
    },
  },
  retrospective: {
    stage: "stage-09",
    artifact: "pipeline/retrospective.md",
    template: "retrospective-template.md",
    gate: {
      agent: "principal",
      severity: "green",
      lessons_promoted: [],
      patterns_harvested: 0,
      contributions_written: [],
    },
  },
};

function exists(relativePath) {
  return fs.existsSync(path.join(ROOT, relativePath));
}

function runNodeScript(script, args = []) {
  const result = spawnSync(process.execPath, [path.join(__dirname, script), ...args], {
    cwd: ROOT,
    encoding: "utf8",
    stdio: "inherit",
  });
  return result.status || 0;
}

function readTemplate(name) {
  return fs.readFileSync(path.join(TEMPLATE_DIR, name), "utf8");
}

function writeIfMissing(relativePath, content) {
  const full = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  if (!fs.existsSync(full)) {
    fs.writeFileSync(full, content.endsWith("\n") ? content : `${content}\n`);
    return true;
  }
  return false;
}

function currentTrack() {
  return "full";
}

function draftGate(stageConfig) {
  const gate = {
    stage: stageConfig.stage,
    status: "FAIL",
    agent: stageConfig.gate.agent,
    track: currentTrack(),
    timestamp: new Date().toISOString(),
    blockers: ["Draft gate generated by codex-team stage scaffold"],
    warnings: [],
    ...stageConfig.gate,
  };

  const gatePath = path.join(ROOT, "pipeline", "gates", `${stageConfig.stage}.json`);
  fs.mkdirSync(path.dirname(gatePath), { recursive: true });
  if (!fs.existsSync(gatePath)) {
    fs.writeFileSync(gatePath, `${JSON.stringify(gate, null, 2)}\n`);
    return true;
  }
  return false;
}

function scaffoldStage(name) {
  const config = STAGES[name];
  if (!config) {
    console.error(`Unknown stage: ${name}`);
    console.error(`Known stages: ${Object.keys(STAGES).join(", ")}`);
    return 1;
  }

  const artifactCreated = writeIfMissing(config.artifact, readTemplate(config.template));
  const gateCreated = draftGate(config);
  console.log(`${artifactCreated ? "created" : "exists"} ${config.artifact}`);
  console.log(`${gateCreated ? "created" : "exists"} pipeline/gates/${config.stage}.json`);
  return 0;
}

function newPipeline(name) {
  fs.mkdirSync(path.join(ROOT, "pipeline", "gates"), { recursive: true });
  fs.mkdirSync(path.join(ROOT, "pipeline", "adr"), { recursive: true });
  fs.mkdirSync(path.join(ROOT, "pipeline", "code-review"), { recursive: true });
  writeIfMissing("pipeline/context.md", "# Project Context\n\n## Fix Log\n");
  if (name) {
    fs.appendFileSync(
      path.join(ROOT, "pipeline", "context.md"),
      `\n${new Date().toISOString()} - Pipeline started: ${name}\n`,
    );
  }
  console.log("Pipeline workspace ready.");
  return 0;
}

function reset() {
  const archiveDir = path.join(ROOT, "pipeline", "archive");
  const context = path.join(ROOT, "pipeline", "context.md");
  fs.mkdirSync(archiveDir, { recursive: true });

  if (fs.existsSync(context)) {
    const stamp = new Date().toISOString().replaceAll(":", "-");
    fs.copyFileSync(context, path.join(archiveDir, `context-${stamp}.md`));
  }

  for (const relative of [
    "pipeline/gates",
    "pipeline/code-review",
    "pipeline/adr",
  ]) {
    const full = path.join(ROOT, relative);
    fs.rmSync(full, { recursive: true, force: true });
    fs.mkdirSync(full, { recursive: true });
  }

  console.log("Pipeline runtime state reset. Context archive preserved.");
  return 0;
}

function doctor() {
  const checks = [
    ["AGENTS.md", exists("AGENTS.md")],
    [".codex/config.yml", exists(".codex/config.yml")],
    [".codex/skills/pipeline/SKILL.md", exists(".codex/skills/pipeline/SKILL.md")],
    ["schemas/gate.schema.json", exists("schemas/gate.schema.json")],
    ["scripts/gate-validator.js", exists("scripts/gate-validator.js")],
    ["pipeline/context.md", exists("pipeline/context.md")],
  ];

  let failed = false;
  for (const [name, ok] of checks) {
    console.log(`${ok ? "PASS" : "FAIL"} ${name}`);
    failed = failed || !ok;
  }

  return failed ? 1 : 0;
}

function validate() {
  const lint = runNodeScript("lint-syntax.js");
  if (lint !== 0) return lint;
  return runNodeScript("gate-validator.js");
}

function usage() {
  console.log("Usage: codex-team <status|roadmap|validate|doctor|reset|review|security|runbook|pipeline:new|stage>");
  return 1;
}

function main() {
  const command = process.argv[2];
  if (command === "status") return runNodeScript("status.js");
  if (command === "roadmap") return runNodeScript("roadmap.js");
  if (command === "validate") return validate();
  if (command === "doctor") return doctor();
  if (command === "reset") return reset();
  if (command === "review") return runNodeScript("approval-derivation.js");
  if (command === "security") return runNodeScript("security-heuristic.js", process.argv.slice(3));
  if (command === "runbook") return runNodeScript("runbook-check.js");
  if (command === "pipeline:new") return newPipeline(process.argv.slice(3).join(" "));
  if (command === "stage") return scaffoldStage(process.argv[3]);
  return usage();
}

process.exit(main());
